#!/usr/bin/env python3

"""
mdp: Markdown preprocessor

%!include filename

	Paste contents of filename in-place in current file. Must be at start of
	line. Processed after the line is expanded.

%!define key value

	Define macro name `key` to have value `value`. `key` must be alphanumeric.
	Must be at start of line. Processed after the line is expanded.

%!foobar or %!foobar!

	Expansion of macro key `foobar` to its value. Keys are alphanumeric plus
	underscore. Expansions are recursive (infinitely, so be careful).
	Optionally terminated with a ! to allow concatenatation.
"""

import re
import os.path
import sys

def process_from(filename, globalvars=None):

	pwd = os.path.dirname(os.path.abspath(filename))
	if globalvars is None:
		globalvars = dict()

	def expand(k):
		if k.group(1) in globalvars:
			return globalvars[k.group(1)]
		else:
			return k.group(0)

	for i, l in enumerate(open(filename).readlines()):
		subs_made = True
		while subs_made:
			l_ = re.sub(r"%!([a-zA-Z0-9_]+)!?", expand, l)
			if l_ == l: break
			l = l_

		if g := re.match(r"^%!include\s+(.*)", l):
			target_name = g.group(1)
			target_path = os.path.join(pwd, target_name)
			if not os.path.exists(target_path):
				sys.exit(f"Couldn't find include file: '{target_path}'\n" \
					f"On line {i + 1} of file: '{filename}'")
			try:
				yield from process_from(target_path, globalvars)
			except StopIteration as e:
				pass

		elif g := re.match(r"^%!define\s+(\w+)\s+(.*)", l):
			key = g.group(1)
			val = g.group(2)
			if key in ["define", "include"] or not re.match(r"[a-zA-Z0-9_]+", key):
				sys.exit(f"Illegal macro name: '{key}'\n" \
					f"On line {i + 1} of file: '{filename}'")
			if key in globalvars:
				print(f"Warning: redefining macro '{key}'" \
					f"On line {i + 1} of file: '{filename}'")
			globalvars[key] = val.strip()

		else:
			yield l

if __name__ == "__main__":
	ofile = open(sys.argv[2], "w")
	for l in process_from(sys.argv[1]):
		ofile.write(l)

